id: A8B521674
base_file: fD849.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:29:07.707684
  last_modified_at: 2022-06-17 12:29:07.707687
