id: A8B521674
base_file: fF7C6.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:29:07.708895
  last_modified_at: 2022-06-17 12:29:07.708898
